import Head from "next/head";

//sections
import Header from "../components/sections/index/header";

//requests
import { getCategories } from "../services/getCategories";

import {
    getBestDealsBanners,
    getBestDealsProducts,
} from "../services/bestDeals";
import getIndexBanners from "../services/getIndexBanners";

//types
import { GetStaticProps } from "next";
//      models
import { CategoryRowCard } from "../types/category";
import {
    BestDealsBanners,
    BestDealsProducts,
} from "../types/models/index/bestDeals";
import { banners } from "../types/models/index/banners";

interface Props {
    header: {
        categories: CategoryRowCard[];
        banners: banners;
        bestDealsBanners: BestDealsBanners;
        bestDealsProducts: BestDealsProducts;
    };
}

export default function Home({ header }: Props): JSX.Element {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="pt-3">
                <Header {...header} />
            </main>
        </div>
    );
}

export const getStaticProps: GetStaticProps = async () => {
    return {
        props: {
            header: {
                banners: await getIndexBanners(),
                categories: await getCategories(),
                bestDealsBanners: await getBestDealsBanners(),
                bestDealsProducts: await getBestDealsProducts(),
            },
        },
    };
};
